# Generated by Django 5.0 on 2023-12-17 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('amount_true', models.CharField(default=0)),
                ('amount_false', models.CharField(default=0)),
                ('amount_all', models.CharField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Статистика по пользователям',
            },
        ),
    ]
